name: Nightly Build

on:
  schedule:
    # Запускается каждый день в 2:00 UTC (5:00 по Москве)
    - cron: '35 11 * * *'
  workflow_dispatch:

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-nightly-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-nightly-

      - name: Build with Gradle
        run: ./gradlew --no-daemon clean build
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_23_X64 || '' }}

      - name: Run tests with detailed report
        run: ./gradlew --no-daemon test
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_23_X64 || '' }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ github.run_id }}
          path: |
            build/reports/tests/
            build/test-results/
          retention-days: 7

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts-${{ github.run_id }}
          path: |
            build/libs/
          retention-days: 3